### ISSUE TITLE
See all features grid

### ISSUE THREAD

**Issue by morrinene** [theintern/theintern.github.io#6]
Add grid to site

@jason0x43's notes on the chart comparing Intern to other frameworks: We should add AVA and Jest, possibly drop BusterJS, and should probably reorder them by current popularity (maybe Jest, AVA, Mocha, Jasmine, Karma, Nightwatch, QUnit).

**Comment by jason0x43** [comment]
The new content was added to the grid a few weeks ago (although a review wouldn't hurt).

**Comment by morrinene** [comment]
Completed
